# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Package
      run: dotnet pack --configuration Release

    - name: Add Nuget Source
      run: |
        cd ${{ github.workspace }}/src/HandsontableBlazor
        dotnet nuget add source --username "andrew.w.wooster@gmail.com" --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Excielo/index.json"
        dotnet nuget push "bin/Release/Excielo.Handsontable.Blazor.0.0.1" --source "github"
